### ISSUE TITLE
Missing host address sidekick

### ISSUE THREAD

**Issue by mpkthomasa** [minio/sidekick#41]
I have 4 MinIo servers.
Trying to deploy with: docker stack deploy and the compose file below:
```
sidekick:
    image: minio/sidekick:v0.5.0
    ports:
      - "19999:8999"
    networks:
      - elasticnet
    deploy:
      restart_policy:
        delay: 0s
        max_attempts: 10
        window: 60s
    #
    command: sidekick --address :8999 --health-path=/minio/health/ready --insecure --log http://minio{1...2}:9000 http://minio{3...4}:9000 http://minio{5...6}:9000 http://minio{7...8}:9000`
```

This is the errors I get:
`sidekick: <ERROR> Missing host address sidekick, please use '/sidekick --help'` and then sidekick stops.

I have tried all addresses I can think off without any luck, it is not entirely clear what the error means...

What is it that I am missing or doing wrong?

Best regards,
Thomas
