### ISSUE TITLE
Slower benchmark with Sidekick

### ISSUE THREAD

**Issue by choyuansu** [minio/sidekick#89]
I'm using [minio/warp](https://github.com/minio/warp) to benchmark my MinIO deployment. I tried connecting to the storage nodes directly vs. using Sidekick, and the results from using Sidekick is much slower compared to connecting directly (1200 MiB/s vs 500 MiB/s).

## Expected Behavior
I expect the benchmarks to have similar speed whether I using Sidekick or not. 

## Current Behavior
Using Sidekick results in slower speed.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Assume 4 storage nodes `minio{1...4}.example.com:9000`.
2. Benchmark w/o using Sidekick:
    ```bash
    warp mixed --host=minio{1...4}.example.com:9000 --access-key=ACCESS_KEY --secret-key=SECRET_KEY --autoterm
    ```
4. Benchmark using Sidekick:
    ```bash
    warp mixed --host=localhost:8000 --access-key=ACCESS_KEY --secret-key=SECRET_KEY --autoterm
    ```

## Context
I'm trying to measure the throughput for my MinIO deployment.

## Your Environment
* Version used (`sidekick version`): 2.0.0
* Operating System and version (`uname -a`): Ubuntu 20.04
* Sidekick is run using a container
  ```yaml
  # docker-compose.yaml
  services:
    sidekick:
      image: "minio/sidekick:v2.0.0"
      ports:
        - 8000:8000
      command: --health-path /minio/health/ready --address :8000 http://minio{1...4}.example.com:9000
  
      extra_hosts:
        - minio1.example.com:x.x.x.x
        - minio2.example.com:x.x.x.x
        - minio3.example.com:x.x.x.x
        - minio4.example.com:x.x.x.x
  ```
